---
# Adapted from Jeff Geerling's implementation
# http://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install vagrant

script:
  - cd tests

  # Create new one(s)
  - vagrant up

  # Check the role syntax correction
  - ansible-playbook --syntax-check -vv playbook.yml

  # Applied the role
  - ansible-playbook -vv playbook.yml

  # Verify the idempotence of the role
  - ansible-playbook -vv playbook.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
