---

- name: install redis
  apt: name=redis-server state=present update_cache=yes

- name: configure redis
  template:
    backup: yes
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: 0640
    owner: redis
    group: redis
  notify: restart redis

- name: start redis
  service: name=redis-server state=started enabled=yes
